title: Daniel Agbo
logo: /assets/img/https://github.com/danielagbo44/danielagbo.github.io/blob/main/headshots.png/_circle.png
description: Technical Communicator
#show_downloads: true
theme: jekyll-theme-minimal
